"""
Trading signal generation for Kalshi daily max temperature markets.

Strategy overview
-----------------
For each open Kalshi KBOS temperature market:

1. Parse the temperature threshold implied by the market ticker.
2. Use the ``TemperatureForecast`` to compute P(max >= threshold) for YES
   and P(max < threshold) for NO.
3. Compare each probability to the market's implied probability (mid-price / 100).
4. Compute edge = |model_prob - market_prob| * 100  (in cents of expected value).
5. If edge >= ``settings.min_edge_cents``, generate a signal.

Signals are advisory dicts consumed by ``engine.py`` for order sizing and
submission. No orders are placed in this module.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

import structlog

from src.config import settings
from src.models.forecast import TemperatureForecast
from src.models.market import KalshiMarket, OrderSide, OrderAction

logger = structlog.get_logger(__name__)

_TICKER_TEMP_RE = re.compile(
    r"[BT](\d+(?:\.\d+)?)",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class TradeSignal:
    """An actionable trade signal generated by the strategy.

    Attributes:
        ticker:           Kalshi market ticker.
        action:           Buy or sell.
        side:             YES or NO.
        model_prob:       Strategy's model probability for the chosen side.
        market_prob:      Market-implied probability for the chosen side.
        edge_cents:       Expected-value edge in cents.
        threshold_f:      Temperature threshold implied by the ticker (°F).
        forecast_mean_f:  Forecast mean temperature at signal time (°F).
        generated_at:     UTC timestamp of signal generation.
        strategy_name:    Name of the strategy that produced the signal.
    """

    ticker: str
    action: OrderAction
    side: OrderSide
    model_prob: float
    market_prob: float
    edge_cents: float
    threshold_f: float
    forecast_mean_f: float
    generated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    strategy_name: str = "edge_v1"


def _extract_threshold_f(ticker: str) -> Optional[float]:
    """Parse the temperature threshold from a Kalshi market ticker.

    Kalshi temperature tickers for Boston typically follow a pattern like
    ``KXMAXTEMP-KBOS-25MAR15-B72`` where ``B72`` means "above 72°F" or
    ``T72`` means "target at 72°F".

    Args:
        ticker: Kalshi market ticker string.

    Returns:
        Temperature threshold in Fahrenheit, or None if unparseable.
    """
    match = _TICKER_TEMP_RE.search(ticker)
    if match:
        try:
            return float(match.group(1))
        except ValueError:
            pass
    logger.debug("strategy.parse_threshold.failed", ticker=ticker)
    return None


def evaluate_market(
    market: KalshiMarket,
    forecast: TemperatureForecast,
) -> Optional[TradeSignal]:
    """Evaluate a single market and return a trade signal if edge is sufficient.

    Args:
        market:   The Kalshi market to evaluate.
        forecast: The current temperature forecast for the relevant date.

    Returns:
        A ``TradeSignal`` if edge >= ``settings.min_edge_cents``, else None.
    """
    threshold_f = _extract_threshold_f(market.ticker)
    if threshold_f is None:
        logger.debug("strategy.skip.no_threshold", ticker=market.ticker)
        return None

    if market.yes_bid == 0 and market.yes_ask == 0:
        logger.debug("strategy.skip.no_quotes", ticker=market.ticker)
        return None

    model_prob_yes = forecast.distribution.prob_above(threshold_f)
    model_prob_no = 1.0 - model_prob_yes
    market_prob_yes = market.implied_probability
    market_prob_no = 1.0 - market_prob_yes

    edge_yes = (model_prob_yes - market_prob_yes) * 100.0
    edge_no = (model_prob_no - market_prob_no) * 100.0

    best_side: Optional[OrderSide] = None
    best_edge: float = 0.0

    if edge_yes >= settings.min_edge_cents:
        best_side = OrderSide.YES
        best_edge = edge_yes
    if edge_no >= settings.min_edge_cents and edge_no > edge_yes:
        best_side = OrderSide.NO
        best_edge = edge_no

    if best_side is None:
        logger.debug(
            "strategy.no_edge",
            ticker=market.ticker,
            threshold_f=threshold_f,
            edge_yes=round(edge_yes, 2),
            edge_no=round(edge_no, 2),
            min_edge=settings.min_edge_cents,
        )
        return None

    model_prob = model_prob_yes if best_side == OrderSide.YES else model_prob_no
    market_prob = market_prob_yes if best_side == OrderSide.YES else market_prob_no

    signal = TradeSignal(
        ticker=market.ticker,
        action=OrderAction.BUY,
        side=best_side,
        model_prob=round(model_prob, 4),
        market_prob=round(market_prob, 4),
        edge_cents=round(best_edge, 2),
        threshold_f=threshold_f,
        forecast_mean_f=forecast.mean_f,
    )

    logger.info(
        "strategy.signal_generated",
        ticker=market.ticker,
        side=best_side.value,
        threshold_f=threshold_f,
        model_prob=round(model_prob, 3),
        market_prob=round(market_prob, 3),
        edge_cents=round(best_edge, 2),
        forecast_mean_f=forecast.mean_f,
    )
    return signal


def scan_markets(
    markets: list[KalshiMarket],
    forecast: TemperatureForecast,
) -> list[TradeSignal]:
    """Evaluate all open markets against the current forecast.

    Args:
        markets:  List of open ``KalshiMarket`` objects.
        forecast: Current ``TemperatureForecast``.

    Returns:
        List of ``TradeSignal`` objects sorted by descending edge.
    """
    signals: list[TradeSignal] = []
    for market in markets:
        if market.status.value != "open":
            continue
        signal = evaluate_market(market, forecast)
        if signal:
            signals.append(signal)

    signals.sort(key=lambda s: -s.edge_cents)
    logger.info(
        "strategy.scan_complete",
        markets_evaluated=len(markets),
        signals_generated=len(signals),
    )
    return signals
